//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashFlowFinance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gasto
    {
        public int GastoId { get; set; }
        public int TipoGastoId { get; set; }
        public string Nombre { get; set; }
        public System.DateTime Fecha { get; set; }
        public int FaimliaId { get; set; }
        public double Costo { get; set; }
    
        public virtual Familia Familia { get; set; }
        public virtual TipoGasto TipoGasto { get; set; }
    }
}
