//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashFlowFinance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int PersonaId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> FamiliaId { get; set; }
        public Nullable<int> MiembroId { get; set; }
        public Nullable<double> SueldoAnio { get; set; }
        public Nullable<double> SueldoNeto { get; set; }
        public Nullable<double> SueldoBruto { get; set; }
        public Nullable<int> AFPId { get; set; }
        public Nullable<int> ImpuestoId { get; set; }
        public Nullable<int> OcupacionId { get; set; }
    
        public virtual AFP AFP { get; set; }
        public virtual Familia Familia { get; set; }
        public virtual Impuesto Impuesto { get; set; }
        public virtual Miembro Miembro { get; set; }
        public virtual Ocupacion Ocupacion { get; set; }
    }
}
