//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashFlowFinance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persona()
        {
            this.Gasto = new HashSet<Gasto>();
            this.Ingreso = new HashSet<Ingreso>();
        }
    
        public int PersonaId { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<int> FamiliaId { get; set; }
        public Nullable<int> MiembroId { get; set; }
        public Nullable<double> SueldoAnio { get; set; }
        public Nullable<double> SueldoNeto { get; set; }
        public Nullable<double> SueldoBruto { get; set; }
        public Nullable<int> AFPId { get; set; }
        public Nullable<int> ImpuestoId { get; set; }
        public Nullable<int> OcupacionId { get; set; }
        public string Foto { get; set; }
        public double Essalud { get; set; }
    
        public virtual AFP AFP { get; set; }
        public virtual Familia Familia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gasto> Gasto { get; set; }
        public virtual Impuesto Impuesto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingreso> Ingreso { get; set; }
        public virtual Miembro Miembro { get; set; }
        public virtual Ocupacion Ocupacion { get; set; }
    }
}
